-- .npc entry
local BAG_VENDOR_IRONFORGE = 5132
local BAG_VENDOR_STORMWIND = 1321
local BAG_VENDOR_DARNASSUS = 4230
local BAG_VENDOR_EXODAR = 16709

local BAG_VENDOR_OGRIMMAR = 3369
local BAG_VENDOR_UNDERCITY = 4590
local BAG_VENDOR_THUNDER_BLUFF = 8364
local BAG_VENDOR_SILVERMOON = 16690

local BAG_NETHERWEAVE = 21841
local BAG_FROSTWEAVE = 41599

local vendors = {BAG_VENDOR_IRONFORGE, BAG_VENDOR_STORMWIND, BAG_VENDOR_DARNASSUS, BAG_VENDOR_EXODAR, BAG_VENDOR_OGRIMMAR, BAG_VENDOR_UNDERCITY, BAG_VENDOR_THUNDER_BLUFF, BAG_VENDOR_SILVERMOON}

-- Add bags
for i = 1, 8 do
    AddVendorItem(vendors[i], BAG_NETHERWEAVE, 0, 0, 0)
    AddVendorItem(vendors[i], BAG_FROSTWEAVE, 0, 0, 0)
end

-- Remove bags
-- for i = 1, 8 do
--    VendorRemoveItem(vendors[i], BAG_NETHERWEAVE)
--    VendorRemoveItem(vendors[i], BAG_FROSTWEAVE)
-- end
